"""empty message

Revision ID: 157dbb8bb494
Revises: 3baa284f2c01
Create Date: 2020-02-07 23:15:38.617169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157dbb8bb494'
down_revision = '3baa284f2c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_constraint('stu_course_ibfk_1', 'stu_course', type_='foreignkey')
    op.drop_constraint('stu_course_ibfk_2', 'stu_course', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('stu_course_ibfk_2', 'stu_course', 'student', ['stu_id'], ['id'])
    op.create_foreign_key('stu_course_ibfk_1', 'stu_course', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
