"""empty message

Revision ID: 29c89a5db17c
Revises: f908c1188c51
Create Date: 2020-02-08 03:44:00.796582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29c89a5db17c'
down_revision = 'f908c1188c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('middle',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('left_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('right_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['left.id'], name='association_ibfk_1'),
    sa.ForeignKeyConstraint(['right_id'], ['right.id'], name='association_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('middle')
    # ### end Alembic commands ###
