"""empty message

Revision ID: 3baa284f2c01
Revises: 5488011efac1
Create Date: 2020-02-07 10:49:13.010184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baa284f2c01'
down_revision = '5488011efac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stu_course', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'stu_course', 'student', ['stu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stu_course', type_='foreignkey')
    op.drop_constraint(None, 'stu_course', type_='foreignkey')
    # ### end Alembic commands ###
