"""empty message

Revision ID: 4facbbb6213f
Revises: 2226f430702a
Create Date: 2020-02-06 08:06:52.024469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4facbbb6213f'
down_revision = '2226f430702a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('user_group_ibfk_1', table_name='user_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_group_ibfk_1', 'user_group', ['group_id'], unique=False)
    op.drop_column('user_group', 'id')
    # ### end Alembic commands ###
