"""empty message

Revision ID: bbdb2163fc87
Revises: 67d0e5d07e0c
Create Date: 2020-02-05 20:18:24.960510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdb2163fc87'
down_revision = '67d0e5d07e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_ibfk_2', 'user_group', type_='foreignkey')
    op.drop_constraint('user_group_ibfk_1', 'user_group', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_group_ibfk_1', 'user_group', 'group', ['group_id'], ['id'])
    op.create_foreign_key('user_group_ibfk_2', 'user_group', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
